In [1]:
import numpy as np

1) Manuel değerleri el ile girerek 3 boyutlu bir array oluşturup bir değişkene atayın. Ardından 3 boyutlu olup olmadığına bakmak için dimension'ını kontrol edin.

In [64]:
arr1 = np.array([[[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]]])

In [65]:
arr1.ndim

3

2) 34, 40, 46, 52... 112 şeklinde devam eden 1 boyutlu bir array oluşturun.

In [66]:
arr2 = np.arange(34,113,6)
arr2

array([ 34,  40,  46,  52,  58,  64,  70,  76,  82,  88,  94, 100, 106,
       112])

3) 50-500 arasında lineer artış gösteren 91 tane tam sayıdan oluşan bir array oluşturun.(dtype'ı int olsun)

In [68]:
arr3 = np.linspace(50, 500, 91, dtype = int)
arr3

array([ 50,  55,  60,  65,  70,  75,  80,  85,  90,  95, 100, 105, 110,
       115, 120, 125, 130, 135, 140, 145, 150, 155, 160, 165, 170, 175,
       180, 185, 190, 195, 200, 205, 210, 215, 220, 225, 230, 235, 240,
       245, 250, 255, 260, 265, 270, 275, 280, 285, 290, 295, 300, 305,
       310, 315, 320, 325, 330, 335, 340, 345, 350, 355, 360, 365, 370,
       375, 380, 385, 390, 395, 400, 405, 410, 415, 420, 425, 430, 435,
       440, 445, 450, 455, 460, 465, 470, 475, 480, 485, 490, 495, 500])

4) 100(10^2) ile 10000(10^5) arasında logaritmik artış gösteren 8 sayıdan oluşan bir array oluşturun.

In [69]:
arr4 = np.logspace(2,5,8)
arr4

array([   100.        ,    268.26957953,    719.685673  ,   1930.69772888,
         5179.47467923,  13894.95494373,  37275.93720315, 100000.        ])

5) 0-8 tam arasındaki ardışık tam sayılardan oluşan(0 ve 8 dahil toplam 9 değer) 3x3 shape'inde bir matris oluşturun.

In [70]:
arr5 = np.arange(0,9).reshape(3,3)
arr5

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

6) 6x6 formatında bir sıfır matrisi oluşturun. (dtype'ı int olsun)

In [71]:
arr6 = np.zeros((6,6), dtype = int)
arr6

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

7) 4x4 formatında, bir matrisi oluşturun. (dtype'ı int olsun)

In [73]:
arr7 = np.ones((4,4), dtype = int)
arr7

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

8) 8x8 formatında bir birim matris oluşturun. (Sadece sol köşegeni 1 geri kalan değerleri 0 olan matris'e birim matris deniyor.) (dtype'ı int olsun)

In [74]:
arr8 = np.eye(8, dtype = int)
arr8

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1]])

9) 5x5 formatında bir köşegen matrisi oluşturun. (Sadece sol üstten sağ alta doğru olan köşegendeki değerleri 3 olsun diğer bütün değerleri 0)

In [75]:
arr9 = np.eye(5, dtype = int)*3
arr9

array([[3, 0, 0, 0, 0],
       [0, 3, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 3]])

10) np.random modülünden uygun fonksiyonu kullanarak 0-1 arasında toplam 6 tane değerden oluşan 1 boyutlu bir array oluşturun.

In [76]:
arr10 = np.random.rand(6)
arr10

array([0.35608528, 0.74985352, 0.82240616, 0.58752385, 0.79664561,
       0.79882444])

11) np.random modülünden uygun fonksiyonu kullanarak 50-100 arasındaki(50 ve 100 dahil) tam sayılardan 10 tanesiyle oluşan (5,2) shape'inde bir array oluşturun. Ardından bu arrayin shape'ini kontrol edin.

In [77]:
arr11 = np.random.randint(50,101,(5,2))
arr11.shape

(5, 2)

12) np.random modülünden uygun fonksiyonu kullanarak 100-1000(1000 dahil değil) arasındaki tam sayılardan rastgele 50 tanesinden oluşan (2,5,5) shape'inde 3 boyutlu bir array oluşturun. Ardından bu array'in dimension'ını(boyutunu) ve shape'ini kontrol edin.

In [78]:
arr12 = np.random.randint(100,1000,(2,5,5))
print(f"Dimension: {arr12.ndim}\nShape: {arr12.shape}")

Dimension: 3
Shape: (2, 5, 5)


13) np.random modülünden uygun fonksiyonu kullanarak 0-100(0 ve 100 dahil) arasındaki tam sayılardan 10 tane seçerek bir array oluşturun. Bu array'in maximum, mininmum değerlerine ve bu değerlerin indexlerine bakın.

In [79]:
arr13 = np.random.randint(0,101,10)
print(f"Maximuum Value: {arr13.max()} - Index: {arr13.argmax()}\nMinimum Value: {arr13.min()} - Index: {arr13.argmin()}")

Maximuum Value: 72 - Index: 9
Minimum Value: 1 - Index: 2


14) np.random modülünden uygun fonksiyonu kullanarak 300-500(300 ve 500 dahil) arasındaki tam sayılardan 20 tane seçerek (2,2,5) shape'inde 3 boyutlu bir array oluşturun. Ardından bu array'in içindeki 20 tam sayı arasından maximum ve minimum değerleri manuel olarak tespit edin ve indexleme yaparak çekmeye çalışın.

In [80]:
arr14 = np.random.randint(300,501,(2,2,5))
arr14

array([[[388, 374, 371, 332, 415],
        [351, 349, 345, 397, 431]],

       [[422, 433, 388, 470, 372],
        [367, 384, 394, 412, 464]]])

In [81]:
print(f"Maximum Value = {arr14[1][0][3]}\nMinimum Value: {arr14[0][0][3]}")

Maximum Value = 470
Minimum Value: 332


15) 0-50(50 dahil) arasındaki ardışık tam sayılardan oluşan bir array oluşturun. Ardından bu arrayin 20. ve 35. indexleri arasındaki değerleri 500'e eşitleyin ve yeni oluşan array'i ekrana yazdırarak broadcasting işleminin yapılıp yapılmadığını test edin.

In [82]:
arr15 = np.arange(0,51)
arr15[20:36] = 500
arr15 

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19, 500, 500, 500, 500, 500, 500,
       500, 500, 500, 500, 500, 500, 500, 500, 500, 500,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50])