In [1]:
import numpy as np

1) 0-29 arası(29 dahil, toplam 30 tam sayı) tam sayılardan oluşan bir boyutlu bir array oluşturun ardından bu array'in shape'ini (15,2) şeklinde güncelleyip 2 boyutlu hale getirin.

In [2]:
arr1 = np.arange(0,30).reshape(15,2)
arr1

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29]])

2) 60 adet rastgele tam sayı verilerinden oluşan bir boyutlu bir array oluşturun. Devamında bu array'i istediğiniz shapelerde 3 boyutlu hale getirin ve son durumda oluşan array'in boyutunu ve shape'ini kontrol edin.


In [3]:
arr2 = np.random.randint(0,100,60).reshape(3,4,5)
arr2

array([[[92, 94, 21, 81, 34],
        [13, 87, 86, 77, 49],
        [ 1, 73, 54, 76, 86],
        [95, 18, 39, 96, 16]],

       [[73, 43, 25,  4, 13],
        [49, 12, 52,  9,  3],
        [27, 99, 33,  4, 87],
        [62, 76,  9, 64,  6]],

       [[62, 82, 18, 43, 19],
        [14, 26, 33, 86, 35],
        [ 9,  4,  8, 36, 19],
        [38, 40,  8, 50, 36]]])

3) 20 elemanlı ve sadece rakamlardan oluşan iki boyutlu bir array oluşturun. Ardından bu array'i düzleştirin ve tek boyutlu hale getirin ve son durumda oluşan array'in boyutunu ve shape'ini kontrol edin.


In [4]:
arr3 = np.random.randint(0,10,(5,4))
arr3

array([[7, 7, 4, 3],
       [9, 8, 7, 6],
       [9, 7, 5, 3],
       [7, 3, 1, 2],
       [0, 9, 5, 0]])

In [5]:
arr3 = arr3.reshape(-1)
arr3

array([7, 7, 4, 3, 9, 8, 7, 6, 9, 7, 5, 3, 7, 3, 1, 2, 0, 9, 5, 0])

In [6]:
print(f"Boyut: {arr3.ndim}\nShape: {arr3.shape}")

Boyut: 1
Shape: (20,)


4) İstediğiniz herhangi elemanlardan oluşan 2 Boyutlu bir array oluşturun. Oluşturduğunuz bu 2 boyutlu array'in içindeki bütün elemanları hem yavaş yol olan for döngüsüyle hem de daha hızlı yol olan uygun NumPy metoduyla tek tek dönerek ekrana yazdırın.


In [7]:
arr4 = np.arange(20).reshape(4,5)
arr4

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [8]:
for x in arr4:
  for y in x:
    print(y)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [9]:
for i in np.nditer(arr4):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


5) 5,10,15,20,25,30 değerlerinden oluşan bir boyutlu bir array ve
   1,2,3,4,5,6 değerlerinden oluşan başka bir boyutlu bir array oluşturun.
   Bu arraylerinin elemanlarına kendi aralarında 4 işlem uygulayın. İki arrayinde 1.indexindekiler toplansın/çıkartılsın/çarpılsın/bölünsün gibi.


In [10]:
arr51 = np.array([5,10,15,20,25,30])
arr52 = np.array([1,2,3,4,5,6])

In [11]:
toplam = arr51.__add__(arr52) # or arr51 + arr52
fark = arr51.__sub__(arr52) # or arr51 - arr52
carpim = arr51 * arr52
bolum = arr51 / arr52

In [12]:
print(f"Toplam: {toplam}\nFark: {fark}\nÇarpım: {carpim}\nBölüm: {bolum}")

Toplam: [ 6 12 18 24 30 36]
Fark: [ 4  8 12 16 20 24]
Çarpım: [  5  20  45  80 125 180]
Bölüm: [5. 5. 5. 5. 5. 5.]


6) 0-100 arası rastgele 10 tam sayıdan oluşan bir array oluşturun ve oluşturulan arrayin sum/mean/max/var/std değerlerini inceleyin.

In [13]:
arr6 = np.random.randint(0,100,10)
arr6

array([49, 40, 42, 68, 97, 29, 31, 55,  8, 66])

In [14]:
sum = arr6.sum()
mean = arr6.mean()
max = arr6.max()
var = arr6.var()
std = arr6.std()

In [15]:
print(f"Toplam: {sum}\nOrtalama: {mean}\nMaksimum: {max}\nVaryans: {var}\nStandart Sapma: {std}")

Toplam: 485
Ortalama: 48.5
Maksimum: 97
Varyans: 552.25
Standart Sapma: 23.5


7) 0-20 arası(20 dahil değil) tam sayılardan oluşan ve 500-530(530 dahil) arası tam sayılardan oluşan 2 array oluşturun. Ardından bu iki array'i concatenate ederek ekrana yazdırın.


In [16]:
arr71 = np.arange(0,21)
arr72 = np.arange(500,531)

In [17]:
np.concatenate([arr71,arr72],axis = 0)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20, 500, 501, 502, 503, 504,
       505, 506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517,
       518, 519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530])

8) 15-50(50 dahil) arası tam sayılardan oluşan bir array oluşturun. Daha sonra 10-100 arası(100 dahil) tam sayılardan oluşan 2.bir array oluşturun. Bu 2 arrayi concatanate ederek 3.bir array oluşturun ve bu array'in 25.index ile 50.index'i(50 dahil) arasındaki değerlerini 888 yapın.

In [18]:
arr81 = np.arange(15,51)
arr82 = np.arange(10,101)
arr83 = np.concatenate([arr81,arr82], axis = 0)

In [19]:
arr83[25:51] = 888
arr83

array([ 15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
        28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39, 888,
       888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888,
       888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

9) 0-40(40 dahil değil) arası değerlerden oluşan (8,5) shape'inde 2 boyutlu bir array ve  320-360(360 dahil değil) değerlerinden oluşan (8,5) shape'inde 2 boyutlu başka bir array oluşturun. Devamında bu iki array'i hem axis = 0'da hem de axis = 1'de concatenate ederek farkı karşılaştırın.


In [20]:
arr91 = np.arange(0,40).reshape(8,5)
arr92 = np.arange(320,360).reshape(8,5)

In [21]:
arr93 = np.concatenate([arr91,arr92], axis = 0)
arr93

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38,  39],
       [320, 321, 322, 323, 324],
       [325, 326, 327, 328, 329],
       [330, 331, 332, 333, 334],
       [335, 336, 337, 338, 339],
       [340, 341, 342, 343, 344],
       [345, 346, 347, 348, 349],
       [350, 351, 352, 353, 354],
       [355, 356, 357, 358, 359]])

In [22]:
arr94 = np.concatenate([arr91,arr92], axis = 1)
arr94

array([[  0,   1,   2,   3,   4, 320, 321, 322, 323, 324],
       [  5,   6,   7,   8,   9, 325, 326, 327, 328, 329],
       [ 10,  11,  12,  13,  14, 330, 331, 332, 333, 334],
       [ 15,  16,  17,  18,  19, 335, 336, 337, 338, 339],
       [ 20,  21,  22,  23,  24, 340, 341, 342, 343, 344],
       [ 25,  26,  27,  28,  29, 345, 346, 347, 348, 349],
       [ 30,  31,  32,  33,  34, 350, 351, 352, 353, 354],
       [ 35,  36,  37,  38,  39, 355, 356, 357, 358, 359]])

10) 9.Soruda oluşturduğunuz 2 array'i axis = 2'de concatenate etmeye çalışın. Ardından axis = 2'de stacklemeye(yığınlamaya) çalışın. İkisi arasındaki farkı karşılaştırın.


In [68]:
arr10 = np.concatenate([arr91,arr92], axis = 2)

AxisError: ignored

In [23]:
arr101 = np.stack([arr91,arr92],axis = 2)
arr101

array([[[  0, 320],
        [  1, 321],
        [  2, 322],
        [  3, 323],
        [  4, 324]],

       [[  5, 325],
        [  6, 326],
        [  7, 327],
        [  8, 328],
        [  9, 329]],

       [[ 10, 330],
        [ 11, 331],
        [ 12, 332],
        [ 13, 333],
        [ 14, 334]],

       [[ 15, 335],
        [ 16, 336],
        [ 17, 337],
        [ 18, 338],
        [ 19, 339]],

       [[ 20, 340],
        [ 21, 341],
        [ 22, 342],
        [ 23, 343],
        [ 24, 344]],

       [[ 25, 345],
        [ 26, 346],
        [ 27, 347],
        [ 28, 348],
        [ 29, 349]],

       [[ 30, 350],
        [ 31, 351],
        [ 32, 352],
        [ 33, 353],
        [ 34, 354]],

       [[ 35, 355],
        [ 36, 356],
        [ 37, 357],
        [ 38, 358],
        [ 39, 359]]])

11) [1, 20, 25, 4, 4, 5, 4, 4, 1, 6, 9, 12, 1, 5] değerlerinden oluşan bir boyutlu bir array oluşturun. Devamında bu array'in içinde değeri 5'e eşit olan değerlerin indexleri bulun.

In [24]:
arr11 = np.array([1, 20, 25, 4, 4, 5, 4, 4, 1, 6, 9, 12, 1, 5])

In [25]:
np.where(arr11 == 5)

(array([ 5, 13]),)

12) Yukarıda oluşturduğunuz array içinde değeri çift olan değerlerin indexlerini bulun.

In [26]:
np.where(arr11 % 2 == 0)

(array([ 1,  3,  4,  6,  7,  9, 11]),)

13) Yukarıda oluşturduğunuz array içinde değeri 4'den büyük olan değerlerin indexlerini bulun.


In [27]:
np.where(arr11 > 4)

(array([ 1,  2,  5,  9, 10, 11, 13]),)

14) Yukarıda oluşturduğunuz array içinde değeri 5'e tam bölünen değerlerin indexlerini bulun.

In [28]:
np.where(arr11 % 5 == 0)

(array([ 1,  2,  5, 13]),)

15) 85-100(100 dahil) arasından rastgele 1 tam sayı seçin

In [29]:
arr15 = np.random.randint(85,101)
np.random.choice(arr15)

78

16) İki basamaklı tam sayılar arasından rastgele sayılar seçerek (3,3) shape'inde bir array oluşturun.

In [30]:
arr16 = np.arange(10,100)
np.random.choice(arr16,(3,3))

array([[10, 40, 60],
       [79, 96, 15],
       [97, 45, 53]])

17) 35-60 arasındaki tam sayılardan bir array oluşturun, ardından bu array içinden rastgele 1 tam sayı seçin.

In [31]:
arr17 = np.arange(35,61)
np.random.choice(arr17)

45

18) Sadece [3, 8, 10, 53] değerlerinden oluşan (2,5) shape'inde 2 boyutlu bir array oluşturun.

In [33]:
arr18 = np.random.choice([3,8,10,53],(2,5))
arr18

array([[ 3, 53,  8, 53, 53],
       [53, 10,  3, 10, 10]])